import { IPropsCard } from '@/types/interfaces';
import imagePath from '@/assets/images/png/card-product-image-example.png';

const ProductCardsData: IPropsCard[] = [
  {
    imagePath,
    rating: 4.8,
    text: 'Кислородный концентратор JAY-10 двухпоточный',
    price: 81938,
    priceBefore: 85348,
    bonus: 450,
    discount: 10,
    onClick: (): void => window.scrollTo({ top: 0, behavior: 'smooth' }),
  },
  {
    imagePath,
    rating: 4.8,
    text: 'Кислородный концентратор JAY-10 двухпоточный',
    price: 81938,
    priceBefore: 85348,
    bonus: 450,
    discount: 10,
    onClick: (): void => window.scrollTo({ top: 0, behavior: 'smooth' }),
  },
  {
    imagePath,
    rating: 4.8,
    text: 'Кислородный концентратор JAY-10 двухпоточный',
    price: 81938,
    priceBefore: 85348,
    bonus: 450,
    discount: 10,
    onClick: (): void => window.scrollTo({ top: 0, behavior: 'smooth' }),
  },
  {
    imagePath,
    rating: 4.8,
    text: 'Кислородный концентратор JAY-10 двухпоточный',
    price: 81938,
    priceBefore: 85348,
    bonus: 450,
    discount: 10,
    onClick: (): void => window.scrollTo({ top: 0, behavior: 'smooth' }),
  },
  {
    imagePath,
    rating: 4.8,
    text: 'Кислородный концентратор JAY-10 двухпоточный',
    price: 81938,
    priceBefore: 85348,
    bonus: 450,
    discount: 10,
    onClick: (): void => window.scrollTo({ top: 0, behavior: 'smooth' }),
  },
  {
    imagePath,
    rating: 4.8,
    text: 'Кислородный концентратор JAY-10 двухпоточный',
    price: 81938,
    priceBefore: 85348,
    bonus: 450,
    discount: 10,
    onClick: (): void => window.scrollTo({ top: 0, behavior: 'smooth' }),
  },
  {
    imagePath,
    rating: 4.8,
    text: 'Кислородный концентратор JAY-10 двухпоточный',
    price: 81938,
    priceBefore: 85348,
    bonus: 450,
    discount: 10,
    onClick: (): void => window.scrollTo({ top: 0, behavior: 'smooth' }),
  },
  {
    imagePath,
    rating: 4.8,
    text: 'Кислородный концентратор JAY-10 двухпоточный',
    price: 81938,
    priceBefore: 85348,
    bonus: 450,
    discount: 10,
    onClick: (): void => window.scrollTo({ top: 0, behavior: 'smooth' }),
  },
];

export default ProductCardsData;
